Areas/Admin/Controllers/LoginClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using startup.Areas.Admin.Models;
using startup.Models;
using startup.Utilities;

namespace startup.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LoginClientController : Controller
    {
        private readonly DataContext _context;
        public LoginClientController(DataContext context)
        {
            _context = context;
        }
        [Route("/Login")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LoginClient(AdminUser user)
        {
            if (user == null)
            {
                return NotFound();
            }
            string pw = Functions.MD5Password(user.Password);

            var check = _context.AdminUsers.Where(m => (m.Email == user.Email) && (m.Password == pw)).FirstOrDefault();
            if (check == null)
            {
                Functions._Message = "Invalid UserName or Password";

                return RedirectToAction("Index", "Login");
            }
            Functions._Message = string.Empty;
            Functions._UserID = check.UserID;
            Functions._UserName = string.IsNullOrEmpty(check.UserName) ? string.Empty : check.UserName;
            Functions._Email = string.IsNullOrEmpty(check.Email) ? string.Empty : check.Email;
            return Redirect("~/");
        }

        

        public IActionResult Logoutclient()
        {
            Functions._UserID = 0;
            Functions._UserName = string.Empty;
            Functions._Email = string.Empty;
            Functions._Message = string.Empty;
            Functions._MessageEmail = string.Empty;

            return Redirect("~/");
        }
    }
}

Areas/Admin/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using startup.Areas.Admin.Models;
using startup.Models;
using startup.Utilities;

namespace startup.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RegisterController : Controller
    {
        private readonly DataContext _context;
        public RegisterController(DataContext context)
        {
            _context = context;
        }

        [Route("/register")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult register(AdminUser user)
        {
            if (user == null) 
            {
                return NotFound();
            }
            Console.WriteLine(user.Email);
            Console.WriteLine(user.Password);
            Console.WriteLine(user.UserName);

            var check = _context.AdminUsers.Where(m => m.Email == user.Email).FirstOrDefault();
            if (check != null) 
            {
                Functions._MessageEmail = "Duplicate Email!";
                return RedirectToAction("Index", "Register");
            }
            Functions._MessageEmail = string.Empty;
            user.Password = Functions.MD5Password(user.Password);
            _context.AdminUsers.Add(user);
            _context.SaveChanges();

            return Redirect("~/login");
        }
    }
}

Areas/Admin/Views/LoginClient/index.cshtml
@using startup.Utilities;
@model startup.Areas.Admin.Models.AdminUser;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="p-5 bg-white" style="    position: fixed;
    top: 50px;
        right: 50%;
    transform: translateX(50%);">
    <form class="row g-3 needs-validation" asp-area="admin" asp-controller="LoginClient" asp-action="LoginClient" novalidate>
        <div class="col-12">
            <label for="yourUsername" class="form-label">Email</label>
            <div class="input-group has-validation">
                <input asp-for="Email" class="form-control" required>
                <div class="invalid-feedback">Please enter your username.</div>
            </div>
        </div>

        <div class="col-12">
            <label for="yourPassword" class="form-label">Password</label>
            <input type="password" asp-for="Password" class="form-control" required>
            <div class="invalid-feedback">Please enter your password!</div>
        </div>

        <div class="col-12 text-center text-danger">
            <h6>
                @Functions._Message
            </h6>
        </div>

        <div class="col-12">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                <label class="form-check-label" for="rememberMe">Remember me</label>
            </div>
        </div>
        <div class="col-12">
            <button class="btn btn-primary w-100" type="submit">Login</button>
        </div>
        <div class="col-12">
            <p class="small mb-0">Don't have account? <a href="/register">Create an account</a></p>
        </div>
    </form>
</div>

Areas/Admin/Views/LoginClient/register.cshtml
@using startup.Utilities;
@model startup.Areas.Admin.Models.AdminUser;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    @* Layout = ""; *@
}

<div class="bg-white p-3 z-index"style="    position: fixed;top: 50px; right: 50%;transform: translateX(50%);">
    <form class="row g-3 needs-validation" novalidate asp-area="Admin" asp-controller="Register" asp-action="Index">
    <div class="col-12">
        <label for="yourName" class="form-label">Your Name</label>
        <input  asp-for="UserName" class="form-control" id="yourName" required>
        <div class="invalid-feedback">Please, enter your name!</div>
    </div>

    <div class="col-12">
        <label for="yourEmail" class="form-label">Your Email</label>
        <input type="email" asp-for="Email" class="form-control" id="yourEmail" required>
        <div class="invalid-feedback">Please enter a valid Email adddress!</div>
    </div>

    <div class="col-12">
        <label for="yourPassword" class="form-label">Password</label>
        <input type="password" asp-for="Password" class="form-control" id="yourPassword" required>
        <div class="invalid-feedback">Please enter your password!</div>
    </div>


    <div class="col-12 text-center text-danger">
        <h6>
            @Functions._MessageEmail
        </h6>
    </div>

    <div class="col-12">
        <button class="btn btn-primary w-100" type="submit">Create Account</button>
    </div>
    <div class="col-12">
        <p class="small mb-0">Already have an account? <a href="/Login">Log in</a></p>
    </div>
</form>
</div>