Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using startup.Models;
using startup.Utilities;

namespace startup.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        private readonly DataContext _context;

        public PostController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            // Tạo danh sách menu cho dropdown
            var mnList = _context.Menus
                .Select(m => new SelectListItem
                {
                    Text = m.MenuName,
                    Value = m.MenuID.ToString()
                })
                .ToList();
            mnList.Insert(0, new SelectListItem()
            {
                Text = "----Select----",
                Value = string.Empty
            });
            ViewBag.mnList = mnList;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        public IActionResult Details(long id)
        {
            var post = _context.Posts.Find(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        public IActionResult Edit(long id)
        {
            var post = _context.Posts.Find(id);

            if (post == null)
            {
                return NotFound();
            }

            // Tương tự như trong Create, bạn cần lấy danh sách menu và truyền vào ViewBag để hiển thị dropdown cho MenuID
            var mnList = _context.Menus
                .Select(m => new SelectListItem
                {
                    Text = m.MenuName,
                    Value = m.MenuID.ToString()
                })
                .ToList();
            mnList.Insert(0, new SelectListItem()
            {
                Text = "----Select----",
                Value = string.Empty
            });
            ViewBag.mnList = mnList;

            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                post.CreatedDate = DateTime.Now; // Gán giá trị CreatedDate
                _context.Update(post);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        public IActionResult Delete(long id)
        {
            var post = _context.Posts.Find(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            var post = _context.Posts.Find(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            var posts = _context.Posts.ToList();

            if (!Functions.IsLogin())
                return RedirectToAction("Index", "Login");

            return View(posts);
        }
    }
}

Areas/Admin/Controllers/UserManageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using startup.Areas.Admin.Models;
using startup.Models;
using startup.Utilities;

namespace startup.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserManageController : Controller
    {
        private readonly DataContext _context;

        public UserManageController(DataContext context)
        {
            _context = context;
        }

        public IActionResult index(){
            var user = _context.AdminUsers.ToList();
            return View(user);
        }


        public IActionResult DeleteU(int? id){
            if(id == null){
                return NotFound();
            }
            var user = _context.AdminUsers.FirstOrDefault(u => u.UserID == id);
            return View(user);
        }
        
        [HttpPost]
        public IActionResult DeleteConfirm(AdminUser id){
            var user = _context.AdminUsers.Find(id.UserID);
            if(user == null){
                return NotFound();
            }
            _context.AdminUsers.Remove(user);
            _context.SaveChanges();
            return RedirectToAction("index");
        }

       
    }
}

Areas/Admin/Views/UserManage/DeleteU.cshtml
@model startup.Areas.Admin.Models.AdminUser

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận xóa người dùng này</h2>
    </div>
    <div class="form-row">
        <div class="tox-form-group--maximize col-md-6">
            <label asp-for="UserID">Mã người dùng</label>
            <input type="text" class="form-control mb-3" asp-for="UserName" disabled>
        </div>
    </div>
    <!--begin form-->
    <form asp-action="DeleteConfirm" asp-controller="UserManage" asp-area="Admin" method="post">
        <input type="hidden" asp-for="UserID" />
        <a class="btn btn-lg btn-warning p-2 mr-5" href="javascript:history.back()">
            <i class="bi bi-arrow-left-circle"></i>Quay lại
        </a>
        <button type="submit" class="btn btn-lg btn-danger p-2">
            <i class="bi bi-trash-fill"></i>Xóa người dùng
        </button>
    </form>
    <!--End Form-->
</main>

Areas/Admin/Views/UserManage/index.cshtml
@using startup.Models;
@model IList<startup.Areas.Admin.Models.AdminUser>
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Danh sách bài viết</h2>
    </div>

    <p>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Post" asp-action="Create">
            <i class="bi bi-file-earmark-text me-1"></i>Thêm bài viết
        </a>
    </p>

    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body mt-4">
                        <table class="table table-borderless datatable">
                            <thead>
                                <tr>
                                    <th class="col-3 text-center">Tên người dùng</th>
                                    <td class="col-2 text-center">Email</td>
                                    <td class="col-1 text-center">Ẩn/hiện</td>
                                    <th class="col-2 text-center">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td class="text-center">@item.UserName</td>
                                        <td class="text-center">@item.Email</td>
                                        <td class="text-center">@item.IsActive</td>
                                        <td class="text-center">
                                            <a asp-area="Admin" asp-controller="UserManage" asp-action="DeleteU"
                                                asp-route-id="@item.UserID" class="btn btn-danger btn-sm"
                                                title="Xóa thông tin người dùng"><i class="bi bi-trash"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>